/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hwtpjsvldagwpwdbweib"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3dHBqc3ZsZGFnd3B3ZGJ3ZWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2NTc1NzgsImV4cCI6MjA4MDIzMzU3OH0.goO_tqydhdCFN9kUZhNrVwWRtnL5heDg-JAUpZ-rkOU"